# Generated by Django 2.2.1 on 2019-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
