# Generated by Django 2.2.1 on 2019-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190507_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='image',
            name='font',
            field=models.CharField(choices=[('Roboto', 'Roboto')], default='Roboto', max_length=100),
        ),
    ]
