# Generated by Django 2.2.1 on 2019-05-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190507_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='images/')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('font', models.CharField(choices=[('Roboto', 'Roboto'), ('Arial', 'Arial')], default='Roboto', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
