# Generated by Django 2.2.1 on 2019-05-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190507_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='blank',
            field=models.ImageField(default=1, upload_to='images/blanks/'),
            preserve_default=False,
        ),
    ]
