# Generated by Django 2.2.1 on 2019-05-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pic_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='size',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='main.Category'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='font',
            field=models.CharField(choices=[('Roboto', 'Roboto-Bold.ttf'), ('Zcool', 'ArZCOOLKuaiLe-Regular.ttf')], default='Roboto', max_length=100),
        ),
    ]
