# Generated by Django 2.2.1 on 2019-05-07 21:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190508_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='pic',
            name='font',
            field=models.CharField(choices=[('Roboto', 'Roboto'), ('ZCOOL', 'ZCOOL')], default='Roboto', max_length=100),
        ),
    ]
