# Generated by Django 2.2.1 on 2019-05-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190508_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='alt_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pic',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
